spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/s_share?serverTimezone=JST&connectionTimezone=SERVER
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
  messages:
    basename: messages/messages, messages/ValidationMessages

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  shutdown: graceful
  servlet:
    session:
      persistent: true
      timeout: 30d
