name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/gradle-build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: artifact
    
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Copy
        run: |
          rsync -av artifact/shusshare.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}
          ssh -t ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf ${{ secrets.DEPLOY_PATH }}/shusshare && unzip ${{ secrets.DEPLOY_PATH }}/shusshare.zip"
      - name: Reboot
        run: |
          ssh -t ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl restart shusshare"
          
          
